using Grynwald.MdDocs.Common.Configuration;

namespace Grynwald.MdDocs.CommandLineHelp.Configuration
{
    public class CommandLineHelpConfiguration : IConfigurationWithMarkdownPresetSetting
    {
        public enum TemplateName
        {
            Default
        }

        public class DefaultTemplateConfiguration
        {

        }

        public class TemplateConfiguration
        {
            public TemplateName Name { get; set; }

            public DefaultTemplateConfiguration Default { get; set; } = new DefaultTemplateConfiguration();
        }


        [ConvertToFullPath]
        public string OutputPath { get; set; } = "";

        public bool IncludeVersion { get; set; }

        [ConvertToFullPath]
        public string AssemblyPath { get; set; } = "";

        public MarkdownPreset MarkdownPreset { get; set; } = MarkdownPreset.Default;

        public bool IncludeAutoGeneratedNotice { get; set; }

        public TemplateConfiguration Template { get; set; } = new TemplateConfiguration();
    }
}
