using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Grynwald.MdDocs.ApiReference.Configuration;
using Grynwald.MdDocs.Common.Configuration;
using Grynwald.Utilities.Configuration;
using Grynwald.Utilities.IO;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Xunit;

namespace Grynwald.MdDocs.ApiReference.Test.Configuration
{
    public class ApiReferenceConfigurationTest : IDisposable
    {
        private readonly TemporaryDirectory m_ConfigurationDirectory = new TemporaryDirectory();
        private readonly string m_ConfigurationFilePath;

        public ApiReferenceConfigurationTest()
        {
            m_ConfigurationFilePath = Path.Combine(m_ConfigurationDirectory, "mddocs.settings.json");

            // clear environment variables (might be set by previous test runs)
            var envVars = Environment.GetEnvironmentVariables(EnvironmentVariableTarget.Process);
            foreach (var key in envVars.Keys.Cast<string>().Where(x => x.StartsWith("MDDOCS__")))
            {
                Environment.SetEnvironmentVariable(key, null, EnvironmentVariableTarget.Process);
            }
        }

        public void Dispose() => m_ConfigurationDirectory.Dispose();

        private void PrepareConfiguration(string key, object value)
        {
            var configRoot = new JObject();

            var currentConfigObject = new JObject();
            configRoot.Add(new JProperty("mddocs", currentConfigObject));

            var keySegments = key.Split(':');
            for (var i = 0; i < keySegments.Length; i++)
            {
                // last fragment => add value
                if (i == keySegments.Length - 1)
                {
                    if (value.GetType().IsArray)
                    {
                        value = JArray.FromObject(value);
                    }

                    currentConfigObject.Add(new JProperty(keySegments[i], value));

                }
                // create child configuration object
                else
                {
                    var newConfigObject = new JObject();
                    currentConfigObject.Add(new JProperty(keySegments[i], newConfigObject));
                    currentConfigObject = newConfigObject;
                }
            }

            var json = configRoot.ToString(Formatting.Indented);
            File.WriteAllText(m_ConfigurationFilePath, json);
        }


        /// <summary>
        /// Gets the assertions that must be true for the default configuration
        /// </summary>
        public static IEnumerable<object[]> DefaultConfigAssertions()
        {
            static object[] TestCase(Action<ApiReferenceConfiguration> assertion)
            {
                return new[] { assertion };
            }

            yield return TestCase(config => Assert.NotNull(config));
            yield return TestCase(config => Assert.Empty(config.OutputPath));
            yield return TestCase(config => Assert.NotNull(config.AssemblyPaths));
            yield return TestCase(config => Assert.Empty(config.AssemblyPaths));
            yield return TestCase(config => Assert.NotNull(config.Template));
            yield return TestCase(config => Assert.Equal(ApiReferenceConfiguration.TemplateName.Default, config.Template.Name));
            yield return TestCase(config => Assert.NotNull(config.Template.Default));
            yield return TestCase(config => Assert.True(config.Template.Default.IncludeAutoGeneratedNotice));
            yield return TestCase(config => Assert.True(config.Template.Default.IncludeVersion));
            yield return TestCase(config => Assert.Equal(MarkdownPreset.Default, config.Template.Default.MarkdownPreset));
        }

        [Theory]
        [MemberData(nameof(DefaultConfigAssertions))]
        public void Default_configuration_is_valid(Action<ApiReferenceConfiguration> assertion)
        {
            var defaultConfig = new ConfigurationProvider().GetDefaultApiReferenceConfiguration();
            assertion(defaultConfig);
        }

        [Theory]
        [MemberData(nameof(DefaultConfigAssertions))]
        public void Empty_configuration_is_valid(Action<ApiReferenceConfiguration> assertion)
        {
            // ARRANGE           
            File.WriteAllText(m_ConfigurationFilePath, "{ }");

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            assertion(config);
        }

        [Theory]
        [MemberData(nameof(DefaultConfigAssertions))]
        public void GetConfiguration_returns_default_configuration_if_config_file_does_not_exist(Action<ApiReferenceConfiguration> assertion)
        {
            var provider = new ConfigurationProvider(m_ConfigurationFilePath);
            var config = provider.GetApiReferenceConfiguration();
            assertion(config);
        }

        [Theory]
        [MemberData(nameof(DefaultConfigAssertions))]
        public void GetConfiguration_returns_default_configuration_if_config_file_path_is_empty(Action<ApiReferenceConfiguration> assertion)
        {
            var provider = new ConfigurationProvider(m_ConfigurationFilePath);
            var config = provider.GetApiReferenceConfiguration();
            assertion(config);
        }

        [Fact]
        public void OutputPath_can_be_set_in_configuration_file()
        {
            // ARRANGE            
            PrepareConfiguration("apireference:outputpath", @"C:\some-path");

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.NotNull(config);
            Assert.Equal(@"C:\some-path", config.OutputPath);
        }

        private class TestClass1
        {
            [ConfigurationValue("mddocs:apireference:outputpath")]
            public string? OutputPath { get; set; }
        }

        [Fact]
        public void OutputPath_can_be_set_through_settings_object()
        {
            // ARRANGE            
            var settings = new TestClass1() { OutputPath = @"C:\some-path" };

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath, settings);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.Equal(@"C:\some-path", config.OutputPath);
        }


        [Fact]
        public void AssemblyPaths_can_be_set_in_configuration_file()
        {
            // ARRANGE            
            PrepareConfiguration("apireference:assemblyPaths", new[] { @"C:\some-path", @"C:\some-other-path" });

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.NotNull(config);
            Assert.Contains(@"C:\some-path", config.AssemblyPaths);
            Assert.Contains(@"C:\some-other-path", config.AssemblyPaths);
        }

        private class TestClass2
        {
            [ConfigurationValue("mddocs:apireference:assemblyPaths")]
            public IEnumerable<string>? AssemblyPaths { get; set; }
        }

        [Fact]
        public void AssemblyPaths_can_be_set_through_settings_object()
        {
            // ARRANGE            
            var settings = new TestClass2() { AssemblyPaths = new[] { @"C:\some-path", @"C:\some-other-path" } };

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath, settings);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.Contains(@"C:\some-path", config.AssemblyPaths);
            Assert.Contains(@"C:\some-other-path", config.AssemblyPaths);
        }

        private class TestClass3
        {
            [ConfigurationValue("mddocs:apireference:assemblyPaths")]
            public IEnumerable<string>? AssemblyPaths { get; set; }
        }

        [Fact]
        public void AssemblyPaths_from_settings_object_override_assembly_paths_from_configuration_file()
        {
            // ARRANGE
            PrepareConfiguration("apireference:assemblyPaths", new[] { @"C:\path1", @"C:\path2", @"C:\path3" });

            var settingsObject = new TestClass3() { AssemblyPaths = new[] { @"C:\path4", @"C:\path5" } };

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath, settingsObject);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.Collection(
                config.AssemblyPaths,
                path => Assert.Equal(@"C:\path4", path),
                path => Assert.Equal(@"C:\path5", path)
            );
        }

        private class TestClass4
        {
            [ConfigurationValue("mddocs:apireference:assemblyPaths")]
            public IEnumerable<string>? AssemblyPaths { get; set; }
        }

        [Fact]
        public void Empty_AssemblyPaths_from_settings_object_do_not_override_assembly_paths_from_configuration()
        {
            // ARRANGE
            PrepareConfiguration("apireference:assemblyPaths", new[] { @"C:\path1", @"C:\path2", @"C:\path3" });

            var settingsObject = new TestClass3() { AssemblyPaths = Array.Empty<string>() };

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath, settingsObject);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.Collection(
                config.AssemblyPaths,
                path => Assert.Equal(@"C:\path1", path),
                path => Assert.Equal(@"C:\path2", path),
                path => Assert.Equal(@"C:\path3", path)
            );
        }


        [Theory]
        [CombinatorialData]
        public void Markdown_preset_can_be_set_in_configuration_file(MarkdownPreset preset)
        {
            // ARRANGE            
            PrepareConfiguration("apireference:template:default:markdownPreset", preset.ToString());

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.NotNull(config);
            Assert.Equal(preset, config.Template.Default.MarkdownPreset);
        }

        private class TestClass5
        {
            [ConfigurationValue("mddocs:apireference:template:default:markdownPreset")]
            public string? Preset { get; set; }
        }

        [Theory]
        [CombinatorialData]
        public void Markdown_preset_can_be_set_through_settings_object(MarkdownPreset preset)
        {
            // ARRANGE            
            var settings = new TestClass5() { Preset = preset.ToString() };

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath, settings);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.NotNull(config);
            Assert.Equal(preset, config.Template.Default.MarkdownPreset);
        }

        [Fact]
        public void GetConfiguration_converts_the_output_path_to_a_full_path()
        {
            // ARRANGE
            var relativePath = "../some-relative-path";
            PrepareConfiguration("apireference:outputPath", relativePath);

            var expectedPath = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(m_ConfigurationFilePath)!, relativePath));

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.NotNull(config);
            Assert.Equal(expectedPath, config.OutputPath);
        }

        [Fact]
        public void GetConfiguration_does_not_change_the_output_path_if_value_is_a_rooted_path()
        {
            // ARRANGE
            var path = @"C:\some-path";
            PrepareConfiguration("apireference:outputPath", path);

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.NotNull(config);
            Assert.Equal(path, config.OutputPath);
        }

        [Fact]
        public void GetConfiguration_converts_the_assembly_paths_to_a_full_path()
        {
            // ARRANGE
            var relativePath1 = "../some-relative-path";
            var relativePath2 = "../some-other-relative-path";
            PrepareConfiguration("apireference:assemblyPaths", new[] { relativePath1, relativePath2 });

            var expectedPath1 = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(m_ConfigurationFilePath)!, relativePath1));
            var expectedPath2 = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(m_ConfigurationFilePath)!, relativePath2));

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.NotNull(config);
            Assert.Contains(expectedPath1, config.AssemblyPaths);
            Assert.Contains(expectedPath2, config.AssemblyPaths);
        }

        [Fact]
        public void GetConfiguration_does_not_change_the_assembly_paths_if_value_is_a_rooted_path()
        {
            // ARRANGE
            var path = @"C:\some-path";
            PrepareConfiguration("apireference:assemblyPaths", new[] { path });

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.NotNull(config);
            var actualPath = Assert.Single(config.AssemblyPaths);
            Assert.Equal(actualPath, path);
        }


        [Theory]
        [CombinatorialData]
        public void IncludeAutoGeneratedNotice_can_be_set_in_configuration_file(bool includeAutoGeneratedNotice)
        {
            // ARRANGE            
            PrepareConfiguration("apireference:template:default:includeAutoGeneratedNotice", includeAutoGeneratedNotice.ToString());

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.NotNull(config);
            Assert.Equal(includeAutoGeneratedNotice, config.Template.Default.IncludeAutoGeneratedNotice);
        }

        private class TestClass6
        {
            [ConfigurationValue("mddocs:apireference:template:default:includeAutoGeneratedNotice")]
            public bool IncludeAutoGeneratedNotice { get; set; }
        }

        [Theory]
        [CombinatorialData]
        public void IncludeAutoGeneratedNotice_can_be_set_through_settings_object(bool includeAutoGeneratedNotice)
        {
            // ARRANGE            
            var settings = new TestClass6() { IncludeAutoGeneratedNotice = includeAutoGeneratedNotice };

            // ACT
            var provider = new ConfigurationProvider(m_ConfigurationFilePath, settings);
            var config = provider.GetApiReferenceConfiguration();

            // ASSERT
            Assert.NotNull(config);
            Assert.Equal(includeAutoGeneratedNotice, config.Template.Default.IncludeAutoGeneratedNotice);
        }
    }
}
