using System.Text;
using Grynwald.MarkdownGenerator;

namespace Grynwald.MdDocs.Common.Pages
{
    public class AutoGeneratedNotice : MdPartial
    {
        private static readonly string s_Comment;

        static AutoGeneratedNotice()
        {
            s_Comment = new StringBuilder()
                .AppendLine("<!--")
                .AppendLine(" ================================================================= ")
                .AppendLine("   Auto-Generated: ")
                .AppendLine("   The contents of this file were generated by a tool.")
                .AppendLine("   Changes to this file may be list if the file is regenerated")
                .AppendLine(" ================================================================= ")
                .AppendLine("-->")
                .ToString();

        }

        protected override MdBlock ConvertToBlock() => new MdParagraph(new MdRawMarkdownSpan(s_Comment));
    }
}
