using Grynwald.MarkdownGenerator;

namespace Grynwald.MdDocs.Common.Pages
{
    public sealed class PageFooter : MdPartial
    {
        protected override MdBlock ConvertToBlock()
        {
            return new MdContainerBlock(
                new MdThematicBreak(),
                new MdParagraph(new MdEmphasisSpan(new MdCompositeSpan(
                    "Documentation generated by ",
                    new MdLinkSpan("MdDocs", "https://github.com/ap0llo/mddocs")
            ))));
        }
    }
}
